class BillRunner{

    public static void main(String bill[]){
	
	    //ClassName ref = new ClassName();
		Bill ref = new Bill();
		
	    System.out.println("ref billReferenceId started");
		int billReferenceId = ref.billReferenceId;
		System.out.println(billReferenceId);
		billReferenceId = 1;
		System.out.println(billReferenceId);
		billReferenceId = 2;
		System.out.println(billReferenceId);
		billReferenceId = 3;
		System.out.println(billReferenceId);
		billReferenceId = 4;
		System.out.println(billReferenceId);
		billReferenceId = 5;
		System.out.println(billReferenceId);
		billReferenceId = 6;
		System.out.println(billReferenceId);
		billReferenceId = 7;
		System.out.println(billReferenceId);
		billReferenceId = 8;
		System.out.println(billReferenceId);
		billReferenceId = 9;
		System.out.println(billReferenceId);
		billReferenceId = 10;
		System.out.println(billReferenceId);
		System.out.println("ref billReferenceId ended");
		
		System.out.println("ref billSequenceNo started");
		int billSequenceNo = ref.billSequenceNo;
		System.out.println(billSequenceNo);
		billSequenceNo = 01;
		System.out.println(billSequenceNo);
		billSequenceNo = 02;
		System.out.println(billSequenceNo);
		billSequenceNo = 03;
		System.out.println(billSequenceNo);
		billSequenceNo = 04;
		System.out.println(billSequenceNo);
		billSequenceNo = 05;
		System.out.println(billSequenceNo);
		billSequenceNo = 06;
		System.out.println(billSequenceNo);
		billSequenceNo = 07;
		System.out.println(billSequenceNo);
		billSequenceNo = 8;
		System.out.println(billSequenceNo);
		billSequenceNo = 9;
		System.out.println(billSequenceNo);
		billSequenceNo = 10;
		System.out.println(billSequenceNo);
		System.out.println("ref billSequenceNo ended");
		
		System.out.println("ref billIssueDate started");
		String billIssueDate = ref.billIssueDate;
		billIssueDate = "29/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "30/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "01/08/2024";
		System.out.println(billIssueDate);
		billIssueDate = "02/09/2024";
		System.out.println(billIssueDate);
		billIssueDate = "28/08/2024";
		System.out.println(billIssueDate);
		billIssueDate = "10/09/2024";
		System.out.println(billIssueDate);
		billIssueDate = "12/09/2024";
		System.out.println(billIssueDate);
		billIssueDate = "15/09/2024";
		System.out.println(billIssueDate);
		billIssueDate = "20/010/2024";
		System.out.println(billIssueDate);
		billIssueDate = "28/010/2024";
		System.out.println(billIssueDate);
	    System.out.println("ref billIssueDate started");
		
		System.out.println("ref billDueDate started");
		String billDueDate = ref.billDueDate;
		billDueDate = "01/08/2024";
		System.out.println(billDueDate);
		billDueDate = "05/08/2024";
		System.out.println(billDueDate);
		billDueDate = "10/09/2024";
		System.out.println(billDueDate);
		billDueDate = "25/09/2024";
		System.out.println(billDueDate);
		billDueDate = "30/09/2024";
		System.out.println(billDueDate);
		billDueDate = "01/10/2024";
		System.out.println(billDueDate);
		billDueDate = "07/10/2024";
		System.out.println(billDueDate);
		billDueDate = "10/11/2024";
		System.out.println(billDueDate);
		billDueDate = "18/11/2024";
		System.out.println(billDueDate);
		System.out.println("ref billDueDate ended");
		
		System.out.println("ref isBillPaid started");
		boolean isBillPaid = ref.isBillPaid;
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		System.out.println("ref isBillPaid ended");
		
		System.out.println("ref isLatestBill started");
		boolean isLatestBill = ref.isLatestBill;
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		System.out.println("ref isLatestBill ended");
		
		System.out.println("ref isFinalBill started");
		boolean isFinalBill = ref.isFinalBill;
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		System.out.println("ref isFinalBill ended");
		
		System.out.println("ref billAmount started");
		double billAmount = ref.billAmount;
		billAmount = 500.00;
		System.out.println(billAmount);
		billAmount = 1000.00;
		System.out.println(billAmount);
		billAmount = 2090.99;
		System.out.println(billAmount);
		billAmount = 4050.00;
		System.out.println(billAmount);
		billAmount = 3000.09;
		System.out.println(billAmount);
		billAmount = 4500.15;
		System.out.println(billAmount);
		billAmount = 6040.06;
		System.out.println(billAmount);
		billAmount = 2525.99;
		System.out.println(billAmount);
		billAmount = 2708.80;
		System.out.println(billAmount);
		billAmount = 4444.99;
		System.out.println(billAmount);
		billAmount = 5500.00;
		System.out.println(billAmount);
		System.out.println("ref billAmount ended");
		
		System.out.println("ref taxInclusiveBill started");
		boolean taxInclusiveBill = ref.taxInclusiveBill;
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		System.out.println("ref taxInclusiveBill ended");
		
	}

}